apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: metallb-config
data:
  config: |
    address-pools:
    - name: ip-pool
      protocol: layer2
      addresses:
      - 172.18.255.246 - 172.18.255.250
